Repository open-vela/frameworks_bluetooth, pull requests merged in 2025-01, with the labels that each got.

#15 Bluetooth: Rename list.h to avoid name conflicts.
  framework/include/bt_list.h
  framework/include/bt_list_internal.h
  service/profiles/spp/spp_service.c
Labels: bug

#18 bluetooth: Solving heap-buffer-overflow caused by memcpy.
  service/profiles/hfp_hf/hfp_hf_state_machine.c
Labels: bug

#19 [bugfix]: fix type mismatch for GATT cookie of socket ipc
  framework/socket/bt_gattc.c
  framework/socket/bt_gatts.c
  service/ipc/socket/include/bt_message_gattc.h
  service/ipc/socket/include/bt_message_gatts.h
  service/ipc/socket/src/bt_socket_gattc.c
  service/ipc/socket/src/bt_socket_gatts.c
Labels: bug

#21 spp: fix resources are not emptied as SPP profile shutdown
  service/profiles/spp/spp_service.c
Labels: bug

#22 OS-Upgrade: Add a BT storage transformation tool.
  CMakeLists.txt
  Kconfig
  Makefile
  tools/storage_transform.c
Labels: enhancement

#23 Bluetooth: framework/include/bt_gatts.h
  framework/include/bt_gatt_defs.h
  framework/include/bt_gatts.h
Labels: documentation

#24 Bluetooth: framework/include/bt_gattc.h
  framework/include/bt_gattc.h
Labels: documentation

#26 Bluetooth: Add the VSC used for DLF.
  service/vendor/bt_vendor.c
  service/vendor/bt_vendor_actions.h
Labels: enhancement
