Repository open-vela/frameworks_bluetooth, pull requests merged in 2025-05, with the labels that each got.

#116 bluetooth: add active connect sample code
  sample_code/createbond/app_bt_gap.c
  sample_code/createbond/app_bt_message_gap.h
  sample_code/createbond/createbond.c
  sample_code/createbond/createbond.h
Labels: documentation

#124 bluetooth: fix adv stop failure after disable stack.
  service/src/adapter_state.c
  service/src/advertising.c
  service/src/scan_manager.c
  service/stacks/zephyr/sal_adapter_classic_interface.c
  service/stacks/zephyr/sal_adapter_le_interface.c
Labels: bug

#125 bluetooth: fix build error.
  service/src/adapter_service.c
Labels: bug

#111 bluetooth: a2dp: Fix A2DP stuttering issue.
  Kconfig
Labels: bug

#117 bluetooth: add passive connect sample code
  sample_code/acceptbond/acceptbond.c
  sample_code/acceptbond/acceptbond.h
  sample_code/acceptbond/app_bt_gap.c
  sample_code/acceptbond/app_bt_message_gap.h
Labels: documentation

#164 Optimization of power consumption in re-connect when disconnected(0x08).
  service/src/connection_manager.c
Labels: enhancement
